### PR TITLE
No 3dview for proto with no graphical representation

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
Also change `Field Summary` to `Field Description`.

Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-bo/projects/joints/protos/Hinge2JointWithBacklash.proto&type=undefined

### CODE REVIEW

**Review by omichel — CHANGES_REQUESTED** [review]
The sql database file should be updated as well.
In the database, the new field should be named `no_3d_view` to be consistent with others, e.g., `needs_robot_ancestor`.
In the proto files, it should named `no3dView` to be consistent with other, e.g., `nonDeterministic`.
In the  JavaScript code, it should probably be the same as in the proto file.

**Comment by omichel** [comment]
Also, I believe we should avoid to add more ajax requests with individual SQL queries on the same table. Instead we should try to minimize these costly calls by grouping them together. For example, it would be nice to merge the calls to [documentation.php](https://github.com/cyberbotics/webots-cloud/blob/main/httpdocs/ajax/proto/documentation.php), [needs_robot_ancestor.php](https://github.com/cyberbotics/webots-cloud/blob/main/httpdocs/ajax/proto/needs_robot_ancestor.php), [display_3d_view.php](https://github.com/cyberbotics/webots-cloud/blob/testing/httpdocs/ajax/proto/display_3d_view.php) and maybe [insertable.php](https://github.com/cyberbotics/webots-cloud/blob/testing/httpdocs/ajax/proto/insertable.php) into a single call.

**Comment by BenjaminDeleze** [comment]
> Also, I believe we should avoid to add more ajax requests with individual SQL queries on the same table. Instead we should try to minimize these costly calls by grouping them together. For example, it would be nice to merge the calls to [documentation.php](https://github.com/cyberbotics/webots-cloud/blob/main/httpdocs/ajax/proto/documentation.php), [needs_robot_ancestor.php](https://github.com/cyberbotics/webots-cloud/blob/main/httpdocs/ajax/proto/needs_robot_ancestor.php), [display_3d_view.php](https://github.com/cyberbotics/webots-cloud/blob/testing/httpdocs/ajax/proto/display_3d_view.php) and maybe [insertable.php](https://github.com/cyberbotics/webots-cloud/blob/testing/httpdocs/ajax/proto/insertable.php) into a single call.

If feasible for [display_3d_view.php](https://github.com/cyberbotics/webots-cloud/blob/testing/httpdocs/ajax/proto/display_3d_view.php) and [documentation.php](https://github.com/cyberbotics/webots-cloud/blob/main/httpdocs/ajax/proto/documentation.php).

I did not do it initially because we do not always need the information returned by `documentation.php` but it is a good idea to merge the two files, the calls to the two ajax request is done two functions (both in webots-cloud.js) apart so it is no a problem to pass the information.

- [needs_robot_ancestor.php](https://github.com/cyberbotics/webots-cloud/blob/main/httpdocs/ajax/proto/needs_robot_ancestor.php) is called on WebotsJs to determine if we should move the floor when the object is a `Device`. It may be possible to get the information in `webots-cloud` and to add a parameter to pass the information to WebotsJS. I will check.
- [insertable.php](https://github.com/cyberbotics/webots-cloud/blob/testing/httpdocs/ajax/proto/insertable.php) needs to be a standalone. It is called to get the list of nodes that is it possible to insert in a specific field. So it is a totally separate thing.

> In the JavaScript code, it should probably be the same as in the proto file.

In JS we get the `.json` straigth from the .sql so the attribute is named `no_3d_view`

**Comment by BenjaminDeleze** [comment]
https://github.com/cyberbotics/webots/pull/5933 must be reviewed in parallel.

**Review by omichel — APPROVED** [review]
Thank you. It looks better to me this way.

**Pull request merged**
